<?php
// Developed by Dennis Stevense for Digital Deployment

/**
 * Implementation of hook_menu().
 */
function emailkit_statistics_menu() {
  $items = array();
  
  $items['emailkit/statistics'] = array(
    'page callback' => 'emailkit_statistics_page',
    'access callback' => TRUE,
    'file' => 'emailkit_statistics.inc',
  );
  
  return $items;
}

/**
 * Implementation of hook_emailkit_message_build().
 */
function emailkit_statistics_emailkit_message_build($message_id, &$message) {
  // Check whether statistics are enabled for this message
  if (!empty($message['#emailkit_statistics'])) {
    module_load_include('inc', 'emailkit_statistics');
    _emailkit_statistics_message_build($message_id, $message);
  }
}

/**
 * Implementation of hook_emailkit_message_before_send().
 */
function emailkit_statistics_emailkit_message_before_send(&$message, &$destination) {
  // Check whether statistics are enabled for this message
  if (!empty($message['#emailkit_statistics']) && $message['#sending_depth'] == 0) {
    module_load_include('inc', 'emailkit_statistics');
    _emailkit_statistics_message_before_send($message, $destination);
  }
}

/**
 * Implementation of hook_emailkit_message_render().
 */
function emailkit_statistics_emailkit_message_render($message, $format, &$output) {
  // Check whether statistics are enabled for this message
  if (!empty($message['#emailkit_statistics'])) {
    module_load_include('inc', 'emailkit_statistics');
    _emailkit_statistics_message_render($message, $format, $output);
  }
}

/**
 * Implementation of hook_emailkit_message_after_send().
 */
function emailkit_statistics_emailkit_message_after_send($message, $destination, $success) {
  // Check whether statistics are enabled for this message
  if (!empty($message['#emailkit_statistics']) && $message['#sending_depth'] == 0) {
    module_load_include('inc', 'emailkit_statistics');
    _emailkit_statistics_message_after_send($message, $destination, $success);
  }
}
