<?php
// Developed by Dennis Stevense for Digital Deployment

/**
 * Implementation of hook_menu().
 */
function emailkit_statistics_menu() {
  $items = array();
  
  // Note: we use emailkit/s instead of emailkit/statistics, because this might make the URL less conspicuous to spam filters or virus scanners
  $items['emailkit/s'] = array(
    'page callback' => 'emailkit_statistics_page',
    'page arguments' => array(2),
    'access callback' => TRUE,
    'file' => 'emailkit_statistics.inc',
  );
  
  return $items;
}

/**
 * Implementation of hook_emailkit_message_before_send().
 */
function emailkit_statistics_emailkit_message_before_send(&$message, &$destination) {
  // Check whether statistics are enabled for this message
  if (!empty($message['#emailkit_statistics'])) {
    module_load_include('inc', 'emailkit_statistics');
    _emailkit_statistics_message_before_send($message, $destination);
  }
}

/**
 * Implementation of hook_emailkit_message_render().
 */
function emailkit_statistics_emailkit_message_render($message, $format, &$body, &$destination = NULL) {
  // Check whether statistics are enabled for this message
  if (!empty($message['#emailkit_statistics'])) {
    module_load_include('inc', 'emailkit_statistics');
    _emailkit_statistics_message_render($message, $format, $body, $destination);
  }
}

/**
 * Implementation of hook_emailkit_message_after_send().
 */
function emailkit_statistics_emailkit_message_after_send($message, $destination, $success) {
  // Check whether statistics are enabled for this message
  if (!empty($message['#emailkit_statistics'])) {
    module_load_include('inc', 'emailkit_statistics');
    _emailkit_statistics_message_after_send($message, $destination, $success);
  }
}

/**
 * Returns a page that displays statistics for the message with the given token.
 *
 * @param $token The token of the message.
 *
 * @return The page content or NULL if no message for the given token can be found.
 */
function emailkit_statistics_message_page($token) {
  module_load_include('inc', 'emailkit_statistics');
  return _emailkit_statistics_message_page($token);
}
