<?php
// Developed by Dennis Stevense for Digital Deployment

/**
 * Implementation of hook_emailkit_dispatcher_info().
 */
function emailkit_test_emailkit_dispatcher_info() {
  $info = array();

  $info['emailkit_test'] = array(
    '#label' => t('Display on screen and discard'),
    '#destinations' => array('emailkit_default'),
  );
  
  return $info;
}

/**
 * Implementation of hook_dispatcher_send() for the emailkit_test dispatcher.
 */
function emailkit_test_dispatcher_send($dispatcher, $message, $destination) {
  drupal_set_message(t("The following message was supposed to dispatched to the following destination:\n!message!destination", array('!message' => print_r($message, TRUE), '!destination' => print_r($destination, TRUE))));
  
  return TRUE;
}
